export const types = {
  onChecking: '[auth] Checking',
  onLogin: '[auth] Login',
  onLogout: '[auth] Logout',
  onRegister: '[auth] Register',
  onclearMessageError: '[auth] Clear Error Message',
  onShowMessageError: '[auth] Show Message Error',
  onRegister: '[auth] Register',
  onSystem: '[auth] System',
  onClearSuccessMessage: '[auth] Clear Success Message',
  onShowMessageSuccess: '[auth] Show Message Success',
  onConfirmAccount: '[auth] Confirm Account',
  onForgotPassword: '[auth] Forgot Password',
  onUpdateUser: '[auth] Update User',
  onLoadingUser: '[auth] Loading User',

  onLoadingPatients: '[patient] Loading Patient',
  onLoadingAction: '[patient] Loading Action',
  onClearSavedPatient: '[patient] Clear Saved Patient',
  onGetPatients: '[patient] Get Patients',
  onActivePatient: '[patient] Active Patient',
  onAddPatient: '[patient] Add Patient',
  onUpdatePatient: '[patient] Update Patient',
  onDeletePatient: '[patient] Delete Patient',
  onLogoutPatient: '[patient] Logout Patient',

  onOpenModal: '[ui] Open Modal',
  onCloseModal: '[ui] Close Modal',
}